[project]
name = "textbrowser"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "pillow>=12.2.0",
    "pypdf>=6.11.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.15.18",
]
